# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    environment:
      - GOPATH: "/home/circleci/goprojects"

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /home/circleci/goprojects/src/goframework

    steps:
      - checkout
      - run: go get -u github.com/go-sql-driver/mysql
      - run: mkdir ../../bin
      - run: go build -o $GOPATH/bin/lala-profile-server ./app
      - run: ssh -o StrictHostKeyChecking=no -i /home/circleci/.ssh/id_rsa ec2-user@ec2-52-78-179-249.ap-northeast-2.compute.amazonaws.com rm -rf /home/ec2-user/targets/lala-profile-server/lala-profile-server
      - run: scp -o StrictHostKeyChecking=no -r /home/circleci/.ssh/id_rsa /home/circleci/goprojects/bin/lala-profile-server ec2-user@ec2-52-78-179-249.ap-northeast-2.compute.amazonaws.com:/home/ec2-user/targets/lala-profile-server/
      - run: ssh -o StrictHostKeyChecking=no -i /home/circleci/.ssh/id_rsa ec2-user@ec2-52-78-179-249.ap-northeast-2.compute.amazonaws.com /home/ec2-user/targets/lala-profile-server/lala-profile-server &
