# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: ~/goprojects/src/goframework
    steps:
      - checkout
      - run: 
        envronment:
          GOPATH: "${HOME}/.go_workspace:/usr/local/go_workspace:${HOME}/.go_project"
        command: go build ./app
#      - run: ssh -o StrictHostKeyChecking=no -i /home/circleci/.ssh/id_rsa ec2-user@ec2-13-125-241-114.ap-northeast-2.compute.amazonaws.com rm -rf /home/ec2-user/targets/lala-profile-server/app
#      - run: scp -o StrictHostKeyChecking=no -r /home/circleci/.ssh/id_rsa ./go/bin ec2-user@ec2-13-125-241-114.ap-northeast-2.compute.amazonaws.com:/home/ec2-user/targets/lala-profile-server/