package util

// PERSON
const SELECT_PERSON = "SELECT NAME, EMAIL, INTRODUCE, IMAGE_URL, COLOR, BLOG, GITHUB, FACEBOOK FROM PERSON WHERE ID = ?"
const SELECT_PERSON_ALL = "SELECT ID, NAME, EMAIL, INTRODUCE, IMAGE_URL, COLOR, BLOG, GITHUB, FACEBOOK FROM PERSON"
const SELECT_PERSON_ID_BY_PERSON_NAME  = "SELECT ID FROM PERSON WHERE NAME = ?"


// PRJECT
const SELECT_PROJECTS = "SELECT NAME, PERIOD_FROM, PERIOD_TO, INTRODUCE, DESCRIPTION, TECHS, ROLES, LINK FROM PROJECT WHERE PERSON_ID = ? ORDER BY PERIOD_TO DESC"

// PRODUCT
const SELECT_PRODUCT_BY_PERSON = "SELECT pdt.ID, pdt.NAME, pdt.INTRODUCE, pdt.TECHS, pdt.IMAGE_URL FROM PRODUCT pdt, PRODUCT_PERSON_MAP mpp, PERSON psn WHERE pdt.ID = mpp.PRODUCT_ID AND mpp.PERSON_ID = psn.ID AND psn.ID = ?"
const SELECT_PRODUCT_BY_PRODUCT_NAME  = "SELECT ID FROM PRODUCT WHERE NAME = ?"
const SELECT_PRODUCT_BY_PRODUCT_ID = "SELECT ID, NAME, INTRODUCE, TECHS, COLOR, IMAGE_URL FROM PRODUCT WHERE ID = ?"
const SELECT_PRODUCT_DETAIL_BY_PRODUCT_ID  = "SELECT ID, TITLE, DESCRIPTION, IMAGE_URL, PRODUCT_ID FROM PRODUCT_DETAIL WHERE PRODUCT_ID = ?"
const SELECT_COMMENT_BY_PRODUCT_ID = "SELECT ID, EMAIL, MESSAGE, PARENT_ID, PRODUCT_ID, REG_DT, MOD_DT FROM COMMENT WHERE PRODUCT_ID = ?"

const SELECT_PRODUCT_ALL = "SELECT pdt.ID, pdt.NAME, pdt.INTRODUCE, pdt.TECHS, pdt.IMAGE_URL FROM PRODUCT pdt"
const SELECT_PERSON_BY_PRODUCT =
	"SELECT psn.ID, " +
		  "psn.NAME " +
		 ",psn.EMAIL "+
		 ",psn.INTRODUCE "+
		 ",psn.IMAGE_URL "+
   		 ",psn.COLOR "+
		 ",psn.BLOG "+
		 ",psn.GITHUB "+
		 ",psn.FACEBOOK "+
		 "FROM PERSON psn "+
		 ",(SELECT mpp.PERSON_ID AS mppPersonId "+
			"FROM PRODUCT_PERSON_MAP mpp "+
			"WHERE mpp.PRODUCT_ID = ? ) innerMpp "+
 		 "WHERE psn.ID = innerMpp.mppPersonId"
const INSERT_PRODUCT = "INSERT INTO PRODUCT (NAME, INTRODUCE, TECHS, COLOR, IMAGE_URL, REG_DT, MOD_DT) VALUES (?, ?, ?, ?, ?, sysdate(), sysdate())"
const INSERT_PRODUCT_DETAIL = "INSERT INTO PRODUCT_DETAIL (TITLE, DESCRIPTION, IMAGE_URL, PRODUCT_ID, REG_DT, MOD_DT) VALUES (?, ?, ?, ?, sysdate(), sysdate())"