package util

const SELECT_PERSON = "SELECT NAME, EMAIL, INTORUDUCE, IMAGE_URL, REP_COLOR	 ,BLOG, GITHUB, FACEBOOK FROM PERSON WHERE ID = ?"
const SELECT_PERSON_ALL = "SELECT NAME, EMAIL, INTORUDUCE, IMAGE_URL, REP_COLOR	 ,BLOG, GITHUB, FACEBOOK FROM PERSON"
const SELECT_PROJECTS = "SELECT PROJECT_NAME, PERIOD, PERSONAL_ROLE, MAIN_OPERATOR, PROJECT_SUMMARY, RESPONSIBILITIES, USED_TECHNOLOGY, PRIMARY_ROLE, PROJECT_RESULT, LINKED_SITE FROM PROJECT WHERE PERSON_ID = ?"
